// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/werbersondev/token-generator-test/cmd/httpservice/api"
	"sync"
)

// Ensure, that RequestTokenGenerationUseCaseMock does implement api.RequestTokenGenerationUseCase.
// If this is not the case, regenerate this file with moq.
var _ api.RequestTokenGenerationUseCase = &RequestTokenGenerationUseCaseMock{}

// RequestTokenGenerationUseCaseMock is a mock implementation of api.RequestTokenGenerationUseCase.
//
//	func TestSomethingThatUsesRequestTokenGenerationUseCase(t *testing.T) {
//
//		// make and configure a mocked api.RequestTokenGenerationUseCase
//		mockedRequestTokenGenerationUseCase := &RequestTokenGenerationUseCaseMock{
//			RequestTokenGenerationFunc: func(ctx context.Context, projectID string) error {
//				panic("mock out the RequestTokenGeneration method")
//			},
//		}
//
//		// use mockedRequestTokenGenerationUseCase in code that requires api.RequestTokenGenerationUseCase
//		// and then make assertions.
//
//	}
type RequestTokenGenerationUseCaseMock struct {
	// RequestTokenGenerationFunc mocks the RequestTokenGeneration method.
	RequestTokenGenerationFunc func(ctx context.Context, projectID string) error

	// calls tracks calls to the methods.
	calls struct {
		// RequestTokenGeneration holds details about calls to the RequestTokenGeneration method.
		RequestTokenGeneration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
		}
	}
	lockRequestTokenGeneration sync.RWMutex
}

// RequestTokenGeneration calls RequestTokenGenerationFunc.
func (mock *RequestTokenGenerationUseCaseMock) RequestTokenGeneration(ctx context.Context, projectID string) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockRequestTokenGeneration.Lock()
	mock.calls.RequestTokenGeneration = append(mock.calls.RequestTokenGeneration, callInfo)
	mock.lockRequestTokenGeneration.Unlock()
	if mock.RequestTokenGenerationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RequestTokenGenerationFunc(ctx, projectID)
}

// RequestTokenGenerationCalls gets all the calls that were made to RequestTokenGeneration.
// Check the length with:
//
//	len(mockedRequestTokenGenerationUseCase.RequestTokenGenerationCalls())
func (mock *RequestTokenGenerationUseCaseMock) RequestTokenGenerationCalls() []struct {
	Ctx       context.Context
	ProjectID string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
	}
	mock.lockRequestTokenGeneration.RLock()
	calls = mock.calls.RequestTokenGeneration
	mock.lockRequestTokenGeneration.RUnlock()
	return calls
}
